### ISSUE TITLE
Tech Tree constructor color codes at bottom of page missing small constructor and hover constructor.

### ISSUE THREAD

**Issue by Grabber48** [RavienGaming/Reforged-Eden-2#109]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Color coding on tech tree at bottom of page for constructors missing small and hover constructors. If progressing without a base you go suit-> portable-> hover-> mobile to get a constructor for an SV took a bit to figure that out. If you can't change or add to the color coding I recommend on the small vehicle tree remove the RCS from the first line and replace it with the hover constructor and put the RCS by itself on a third branch so people can see the requirement.

**Comment by VermillionX** [comment]
Hover and Mobile Constructor use the same constructor class. Anything that can be made in the Mobile Constructor on the tech tree can be made in the Hover Constructor.
And no, it is not changeable.
What does the position of the RCS in the tech tree have to do with the non-existent ability to make a connection between nothing and the SV Constructor?

**Comment by Grabber48** [comment]
> Hover and Mobile Constructor use the same constructor class. Anything that can be made in the Mobile Constructor on the tech tree can be made in the Hover Constructor. And no, it is not changeable. What does the position of the RCS in the tech tree have to do with the non-existent ability to make a connection between nothing and the SV Constructor?

The hover constructor can be made in the portable constructor but the mobile constructor CAN'T,  it can be made in the hover constructor thus the hover is a prerequisite for the mobile constructor. why need to have an RCS before a constructor since they are seldom used? Whatever the reason the tree is wrong the hover is needed before you can make a mobile. Another way to fix would be to add the mobile to the portable menu then you wouldn't have to touch the tech tree.. You can also build a large constructor in a hover but not in the mobile so no you can't build everything in the mobile that you can in the hover so they are not the same class.

**Comment by VermillionX** [comment]
I have moved the RCS out of the generator tree for the next update, since you're right: It doesn't belong there. It's a holdover from vanilla.
It unlocks earlier as a prerequisite for the SV small thruster in the same way that the HV RCS is a prerequisite for the HV Small thruster.

However, The Hover Constructor and the Mobile Constructor craft the exact same items. It is not possible for them to produce different items. I have checked just in case, and I can confirm that both the Mobile and Hover constructor have the same recipes and can craft the same Large Constructor.
The Mobile Constructor will also never be craftable via the Portable Constructor since the Portable Constructor is not capable of processing the basic materials required to craft the Mobile Constructor, which has a different recipe from the Hover Constructor.

In order to clear up potential confusion, both the Hover Constructor and Mobile Constructor will be renamed in the next update to: Mobile Constructor (HV) and Mobile Constructor (SV), with the UI displaying "Mobile Constructor" in the techtree and the constructor for both .

**Comment by Grabber48** [comment]
> I have moved the RCS out of the generator tree for the next update, since you're right: It doesn't belong there. It's a holdover from vanilla. It unlocks earlier as a prerequisite for the SV small thruster in the same way that the HV RCS is a prerequisite for the HV Small thruster.
> 
> However, The Hover Constructor and the Mobile Constructor craft the exact same items. It is not possible for them to produce different items. I have checked just in case, and I can confirm that both the Mobile and Hover constructor have the same recipes and can craft the same Large Constructor. The Mobile Constructor will also never be craftable via the Portable Constructor since the Portable Constructor is not capable of processing the basic materials required to craft the Mobile Constructor, which has a different recipe from the Hover Constructor.
> 
> In order to clear up potential confusion, both the Hover Constructor and Mobile Constructor will be renamed in the next update to: Mobile Constructor (HV) and Mobile Constructor (SV), with the UI displaying "Mobile Constructor" in the techtree and the constructor for both .

Thanks I think I looked at the portable when i meant to look at the mobile about the large constructor, my bad. Are you going to put the hover constructor in where you took out the RCS? I like to start with an SV first but was forced build an HV consisting of a fuel tank generator and constructor to build a mobile constructor for the SV then I find a base like the abandoned factory which already has small constructors and storage and progress from there, find it much faster.
