### ISSUE TITLE
Polaris Auxiliary POI misses satellite dish

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#270]
### Reforged Eden 2 Build Number

19

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The "Polaris Long Range Array" RE2_BA_PolDeco08 misses its big sattelite communication dish. The usual bug with custom parts missing on imported POIs.

### POI Name

RE2_BA_PolDeco08

**Comment by RavienGaming** [comment]
I swear this bug is going to turn all my hair gray!

**Comment by RavienGaming** [comment]
I just checked this, it's fine on my end and the version on the workshop is up to date.

Can you verify if it's bugged for you in SP? Possibly it went missing due to the block mapping bug or outdated prefabs on the server.

![20240814170843_1](https://github.com/user-attachments/assets/3bbdcab9-a4af-4be7-8169-9ef909f6ac28)

**Comment by Ente2k** [comment]
Oh it seems you are correct. Its fine in SP. Anvil issue then it is apparently.
