### ISSUE TITLE
CV Shield unable to turn back on intermittently - sometimes lasting hours or days- despite several file integrity checks

### ISSUE THREAD

**Issue by mythras** [RavienGaming/Reforged-Eden-2#354]
### Reforged Eden 2 Build Number

Build 23

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Title basically explains this - is very annoying 

### Error code from console or log (Optional)

22-13:05:43.047 08_05 -LOG- Task Type=cancel ThreadId=50544 ManagedId=29
Could not find method 'SetLabel' on UIScrollablePopupList
Could not find method 'SetLabel' on UIScrollablePopupList

### POI Name

Myth of Plutus

### Playfield Name

Eloutda Sector

### Star Name

 Amodhaka Star, Anvil

### Game Seed

No permission

**Comment by RavienGaming** [comment]
This is likely due to not having enough shield recharge. Check the PDA to see a list of common issues that may prevent a shield from charging.
If you've ruled out all the issues shown in the PDA and it's still not charging when you're absolutely sure it should be, this would be a game bug. I will attach the bug reporting directions below:

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by mythras** [comment]
I play Empyrion way too much - I know when the shield isn't charging due to low shield output thank you sir- and im not sure i can reproduce it in vanilla cause doubt its happening there
