### ISSUE TITLE
Endless error popups and console flooded with errors on login, making game unplayable

### ISSUE THREAD

**Issue by Claudia-S-C** [RavienGaming/Reforged-Eden-2#377]
### Reforged Eden 2 Build Number

Build 23

### Game mode

Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

A variety of error conditions while logging in. 
![Capture](https://github.com/user-attachments/assets/4c6f1ba7-d069-496c-baa8-9bce8cfced89)
![image](https://github.com/user-attachments/assets/d0a1c41a-0691-452b-9c1c-e44742c98a4a)
![image](https://github.com/user-attachments/assets/75b811ce-fcce-4bad-829f-76e431817911)
![image](https://github.com/user-attachments/assets/92e0bb72-9b39-4af5-b372-52aa75fdaeb0)
this one cant be resolved and marks the beginning of a crash loop, i can attempt to  break the loop by spamming tilde and V
It means that there is a flood of errors currently happening in the console. 
![image](https://github.com/user-attachments/assets/cfc260f5-9199-4964-8e3b-eb272ca77b30)
that error is constantly flooding the console

Troubleshooting steps completed: 
set a body type for character. 
several Restarts
Clear cache folder of it contents
reinstall game on different hard drive, and deleting remains of Empyrion folder on old install
try logging in on completely different playfield
the problem persisted so I made a new vanilla game and had no issues. 
im at my wits end so any help is appreciated. 

### Error code from console or log (Optional)

System ArgumentException an item with the same key has already been added Key:2701967

### POI Name

na

### Playfield Name

na

### Playfield Class

na

### Star Name

na

### Star Class

na

### Mission Name

na

### Mission Objective

na

### Game Seed

unknown

**Comment by RavienGaming** [comment]
The most likely issue for this is an incorrectly installed RE2 scenario on the server side. It's unlikely a client side issue if validating files/restarting your game/etc did not work.

I would try reinstalling the scenario on the server and seeing if that fixes it. Make sure to use binary mode if using a FTP client when you upload the scenario files. I'll keep this open for the mean time, let me know how that turns out.

**Comment by Claudia-S-C** [comment]
the server is HWS  NA, afaik noone else is going through this.

**Comment by Claudia-S-C** [comment]
what item is asset key 2701967 that keeps coming up

**Comment by RavienGaming** [comment]
> what item is asset key 2701967 that keeps coming up

That is typically, but not always, due to an error with a trader config file. I have not been getting that on my end, so that would be an issue on the server.
As far as the shader errors that could be a game bug if no one else is having it. Scenario issues are typically experienced by **everyone** playing the scenario.

It could be a corrupt playfield. I recommend seeking assistance on HWS by putting in a ticket if they have a ticket system for admins to assist you by possibly moving you to a different playfield.

**Comment by Claudia-S-C** [comment]
I do have a ticket in, We are discussing a character reset in which I could potentially lose my tech tree/spent UP so was hoping for some kind of workaround.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by Claudia-S-C** [comment]
Also I did try relogging from another playfield but had the same issues

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by Claudia-S-C** [comment]
The admin did a character reset for me and its solved the problem, so they expect some sort of corruption of the player file

**Comment by RavienGaming** [comment]
Glad they were able to get it fixed for you!
