### ISSUE TITLE
Abandoned Reactor Stone wall issue

### ISSUE THREAD

**Issue by meithtalann** [RavienGaming/Reforged-Eden-2#397]
### Reforged Eden 2 Build Number

Build 24

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

While achieving Abandoned Reactor there is plenty stone wall inside POI. 
Those block the content.
Sometimes when i restart de game those wall disappear.

### POI Name

Abandoned Reactor

### Playfield Name

Alpha III

### Playfield Class

Wind Dune

### Star Name

Alpha

### Game Seed

505801

I did activate god mode to pass thru the wall and then you see the whole room
![20241207104530_1](https://github.com/user-attachments/assets/3a845762-7dc2-43ed-82fe-34c667f2168a)
![20241207104533_1](https://github.com/user-attachments/assets/2833ab7f-cfa5-4957-8502-2989f0c5193e)

**Comment by RavienGaming** [comment]
Are you playing on a dedicated server? If so it's likely a server issue. Otherwise it would be a game bug.

When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
