### ISSUE TITLE
Standard Plasma Turbine emits a "beam" from the front every ~16 seconds while cruising

### ISSUE THREAD

**Issue by Stan2112** [RavienGaming/Reforged-Eden-2#53]
### Reforged Eden 2 Build Number

4

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Very hard to capture a pic.  Happens in both atmo and space.  Every 15-16 seconds of steady-state cruise, a very fast "beam" similar to a laser blast but much faster and less noticeable "fires" out the front of the turbine.  This is different than the normal trail that is emitted from the rear.

Seems to emit in the direction of travel, NOT the direction a ship is facing.  May be more noticeable at faster speeds.  It's very faint at 40 m/s, not so much at 100 m/s.

**Comment by RavienGaming** [comment]
This is due to how the game calculates world coordinates combined with particle effects that are rendered in world space rather than local space.
The "fix" would be to change the particle from world space to local space though I don't know how those models are setup as that's Vermillion's so it may not be as easy as just making that change.
I have a feeling that it's actually a trail renderer, which may not be able to use local space at all.

I have the same issue with the effect projectors like the smoke and fire trails, though in those cases I was able to make some creative tweaks to at least lower the impact of the effect.

**Comment by RavienGaming** [comment]
This should be fixed as of the latest update (Build 6).
If it still happens please open another issue.
